# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhaozeyu/Desktop/study/yutbin_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhaozeyu/Desktop/study/yutbin_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhaozeyu/Desktop/study/yutbin_server/CMakeFiles /home/zhaozeyu/Desktop/study/yutbin_server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhaozeyu/Desktop/study/yutbin_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yutbin_server

# Build rule for target.
yutbin_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yutbin_server
.PHONY : yutbin_server

# fast build rule for target.
yutbin_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/build
.PHONY : yutbin_server/fast

# target to build an object file
src/base/Coroutines.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Coroutines.o
.PHONY : src/base/Coroutines.o

# target to preprocess a source file
src/base/Coroutines.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Coroutines.i
.PHONY : src/base/Coroutines.i

# target to generate assembly for a file
src/base/Coroutines.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Coroutines.s
.PHONY : src/base/Coroutines.s

# target to build an object file
src/base/Thread.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Thread.o
.PHONY : src/base/Thread.o

# target to preprocess a source file
src/base/Thread.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Thread.i
.PHONY : src/base/Thread.i

# target to generate assembly for a file
src/base/Thread.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Thread.s
.PHONY : src/base/Thread.s

# target to build an object file
src/base/Threadpool.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Threadpool.o
.PHONY : src/base/Threadpool.o

# target to preprocess a source file
src/base/Threadpool.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Threadpool.i
.PHONY : src/base/Threadpool.i

# target to generate assembly for a file
src/base/Threadpool.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Threadpool.s
.PHONY : src/base/Threadpool.s

# target to build an object file
src/base/Timestamp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Timestamp.o
.PHONY : src/base/Timestamp.o

# target to preprocess a source file
src/base/Timestamp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Timestamp.i
.PHONY : src/base/Timestamp.i

# target to generate assembly for a file
src/base/Timestamp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/Timestamp.s
.PHONY : src/base/Timestamp.s

# target to build an object file
src/base/asyclogging.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/asyclogging.o
.PHONY : src/base/asyclogging.o

# target to preprocess a source file
src/base/asyclogging.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/asyclogging.i
.PHONY : src/base/asyclogging.i

# target to generate assembly for a file
src/base/asyclogging.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/asyclogging.s
.PHONY : src/base/asyclogging.s

# target to build an object file
src/base/fileutil.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/fileutil.o
.PHONY : src/base/fileutil.o

# target to preprocess a source file
src/base/fileutil.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/fileutil.i
.PHONY : src/base/fileutil.i

# target to generate assembly for a file
src/base/fileutil.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/fileutil.s
.PHONY : src/base/fileutil.s

# target to build an object file
src/base/logfile.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logfile.o
.PHONY : src/base/logfile.o

# target to preprocess a source file
src/base/logfile.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logfile.i
.PHONY : src/base/logfile.i

# target to generate assembly for a file
src/base/logfile.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logfile.s
.PHONY : src/base/logfile.s

# target to build an object file
src/base/logging.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logging.o
.PHONY : src/base/logging.o

# target to preprocess a source file
src/base/logging.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logging.i
.PHONY : src/base/logging.i

# target to generate assembly for a file
src/base/logging.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logging.s
.PHONY : src/base/logging.s

# target to build an object file
src/base/logstream.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logstream.o
.PHONY : src/base/logstream.o

# target to preprocess a source file
src/base/logstream.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logstream.i
.PHONY : src/base/logstream.i

# target to generate assembly for a file
src/base/logstream.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/base/logstream.s
.PHONY : src/base/logstream.s

# target to build an object file
src/net/Acceptor.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Acceptor.o
.PHONY : src/net/Acceptor.o

# target to preprocess a source file
src/net/Acceptor.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Acceptor.i
.PHONY : src/net/Acceptor.i

# target to generate assembly for a file
src/net/Acceptor.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Acceptor.s
.PHONY : src/net/Acceptor.s

# target to build an object file
src/net/Channel.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Channel.o
.PHONY : src/net/Channel.o

# target to preprocess a source file
src/net/Channel.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Channel.i
.PHONY : src/net/Channel.i

# target to generate assembly for a file
src/net/Channel.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Channel.s
.PHONY : src/net/Channel.s

# target to build an object file
src/net/Connector.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Connector.o
.PHONY : src/net/Connector.o

# target to preprocess a source file
src/net/Connector.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Connector.i
.PHONY : src/net/Connector.i

# target to generate assembly for a file
src/net/Connector.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Connector.s
.PHONY : src/net/Connector.s

# target to build an object file
src/net/Eventloop.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Eventloop.o
.PHONY : src/net/Eventloop.o

# target to preprocess a source file
src/net/Eventloop.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Eventloop.i
.PHONY : src/net/Eventloop.i

# target to generate assembly for a file
src/net/Eventloop.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Eventloop.s
.PHONY : src/net/Eventloop.s

# target to build an object file
src/net/EventloopThread.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/EventloopThread.o
.PHONY : src/net/EventloopThread.o

# target to preprocess a source file
src/net/EventloopThread.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/EventloopThread.i
.PHONY : src/net/EventloopThread.i

# target to generate assembly for a file
src/net/EventloopThread.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/EventloopThread.s
.PHONY : src/net/EventloopThread.s

# target to build an object file
src/net/EventloopThreadpool.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/EventloopThreadpool.o
.PHONY : src/net/EventloopThreadpool.o

# target to preprocess a source file
src/net/EventloopThreadpool.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/EventloopThreadpool.i
.PHONY : src/net/EventloopThreadpool.i

# target to generate assembly for a file
src/net/EventloopThreadpool.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/EventloopThreadpool.s
.PHONY : src/net/EventloopThreadpool.s

# target to build an object file
src/net/InetAddress.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/InetAddress.o
.PHONY : src/net/InetAddress.o

# target to preprocess a source file
src/net/InetAddress.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/InetAddress.i
.PHONY : src/net/InetAddress.i

# target to generate assembly for a file
src/net/InetAddress.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/InetAddress.s
.PHONY : src/net/InetAddress.s

# target to build an object file
src/net/Socket.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Socket.o
.PHONY : src/net/Socket.o

# target to preprocess a source file
src/net/Socket.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Socket.i
.PHONY : src/net/Socket.i

# target to generate assembly for a file
src/net/Socket.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Socket.s
.PHONY : src/net/Socket.s

# target to build an object file
src/net/TcpConnection.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/TcpConnection.o
.PHONY : src/net/TcpConnection.o

# target to preprocess a source file
src/net/TcpConnection.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/TcpConnection.i
.PHONY : src/net/TcpConnection.i

# target to generate assembly for a file
src/net/TcpConnection.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/TcpConnection.s
.PHONY : src/net/TcpConnection.s

# target to build an object file
src/net/Tcpclient.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Tcpclient.o
.PHONY : src/net/Tcpclient.o

# target to preprocess a source file
src/net/Tcpclient.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Tcpclient.i
.PHONY : src/net/Tcpclient.i

# target to generate assembly for a file
src/net/Tcpclient.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Tcpclient.s
.PHONY : src/net/Tcpclient.s

# target to build an object file
src/net/Tcpserver.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Tcpserver.o
.PHONY : src/net/Tcpserver.o

# target to preprocess a source file
src/net/Tcpserver.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Tcpserver.i
.PHONY : src/net/Tcpserver.i

# target to generate assembly for a file
src/net/Tcpserver.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Tcpserver.s
.PHONY : src/net/Tcpserver.s

# target to build an object file
src/net/Timequeue.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Timequeue.o
.PHONY : src/net/Timequeue.o

# target to preprocess a source file
src/net/Timequeue.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Timequeue.i
.PHONY : src/net/Timequeue.i

# target to generate assembly for a file
src/net/Timequeue.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/Timequeue.s
.PHONY : src/net/Timequeue.s

# target to build an object file
src/net/netbuffer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/netbuffer.o
.PHONY : src/net/netbuffer.o

# target to preprocess a source file
src/net/netbuffer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/netbuffer.i
.PHONY : src/net/netbuffer.i

# target to generate assembly for a file
src/net/netbuffer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/netbuffer.s
.PHONY : src/net/netbuffer.s

# target to build an object file
src/net/poller.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/poller.o
.PHONY : src/net/poller.o

# target to preprocess a source file
src/net/poller.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/poller.i
.PHONY : src/net/poller.i

# target to generate assembly for a file
src/net/poller.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/src/net/poller.s
.PHONY : src/net/poller.s

# target to build an object file
test/testlog.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/test/testlog.o
.PHONY : test/testlog.o

# target to preprocess a source file
test/testlog.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/test/testlog.i
.PHONY : test/testlog.i

# target to generate assembly for a file
test/testlog.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yutbin_server.dir/build.make CMakeFiles/yutbin_server.dir/test/testlog.s
.PHONY : test/testlog.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yutbin_server"
	@echo "... src/base/Coroutines.o"
	@echo "... src/base/Coroutines.i"
	@echo "... src/base/Coroutines.s"
	@echo "... src/base/Thread.o"
	@echo "... src/base/Thread.i"
	@echo "... src/base/Thread.s"
	@echo "... src/base/Threadpool.o"
	@echo "... src/base/Threadpool.i"
	@echo "... src/base/Threadpool.s"
	@echo "... src/base/Timestamp.o"
	@echo "... src/base/Timestamp.i"
	@echo "... src/base/Timestamp.s"
	@echo "... src/base/asyclogging.o"
	@echo "... src/base/asyclogging.i"
	@echo "... src/base/asyclogging.s"
	@echo "... src/base/fileutil.o"
	@echo "... src/base/fileutil.i"
	@echo "... src/base/fileutil.s"
	@echo "... src/base/logfile.o"
	@echo "... src/base/logfile.i"
	@echo "... src/base/logfile.s"
	@echo "... src/base/logging.o"
	@echo "... src/base/logging.i"
	@echo "... src/base/logging.s"
	@echo "... src/base/logstream.o"
	@echo "... src/base/logstream.i"
	@echo "... src/base/logstream.s"
	@echo "... src/net/Acceptor.o"
	@echo "... src/net/Acceptor.i"
	@echo "... src/net/Acceptor.s"
	@echo "... src/net/Channel.o"
	@echo "... src/net/Channel.i"
	@echo "... src/net/Channel.s"
	@echo "... src/net/Connector.o"
	@echo "... src/net/Connector.i"
	@echo "... src/net/Connector.s"
	@echo "... src/net/Eventloop.o"
	@echo "... src/net/Eventloop.i"
	@echo "... src/net/Eventloop.s"
	@echo "... src/net/EventloopThread.o"
	@echo "... src/net/EventloopThread.i"
	@echo "... src/net/EventloopThread.s"
	@echo "... src/net/EventloopThreadpool.o"
	@echo "... src/net/EventloopThreadpool.i"
	@echo "... src/net/EventloopThreadpool.s"
	@echo "... src/net/InetAddress.o"
	@echo "... src/net/InetAddress.i"
	@echo "... src/net/InetAddress.s"
	@echo "... src/net/Socket.o"
	@echo "... src/net/Socket.i"
	@echo "... src/net/Socket.s"
	@echo "... src/net/TcpConnection.o"
	@echo "... src/net/TcpConnection.i"
	@echo "... src/net/TcpConnection.s"
	@echo "... src/net/Tcpclient.o"
	@echo "... src/net/Tcpclient.i"
	@echo "... src/net/Tcpclient.s"
	@echo "... src/net/Tcpserver.o"
	@echo "... src/net/Tcpserver.i"
	@echo "... src/net/Tcpserver.s"
	@echo "... src/net/Timequeue.o"
	@echo "... src/net/Timequeue.i"
	@echo "... src/net/Timequeue.s"
	@echo "... src/net/netbuffer.o"
	@echo "... src/net/netbuffer.i"
	@echo "... src/net/netbuffer.s"
	@echo "... src/net/poller.o"
	@echo "... src/net/poller.i"
	@echo "... src/net/poller.s"
	@echo "... test/testlog.o"
	@echo "... test/testlog.i"
	@echo "... test/testlog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

